source 'https://rubygems.org'

ruby '3.3.4'

gem 'sinatra'
gem 'mocha', require: false
gem 'redis'
gem 'concurrent-ruby'
gem 'json'
gem 'rackup'
gem 'puma'
gem 'connection_pool'

group :test do
  gem 'rack-test'
  gem 'minitest'
end
