apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: water-tls
  namespace: water
spec:
  dnsNames:
  - water.teamhephy.info
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: water-tls
