apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: water-tls
  namespace: water
spec:
  dnsNames:
  - water.harvey.moomboo.space
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: water-tls
