---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: water-monitor
  namespace: cozy-fluxcd
spec:
  update:
    path: water-dev
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: kingdon+fluxcd@nerdland.info
        name: FluxImageAutomation
      messageTemplate: |
        [skip ci] Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
