apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: water
    type: cmd
  name: water-cmd
  namespace: water
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: water
      type: cmd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: water
        type: cmd
      name: water-cmd
      namespace: water
    spec:
      containers:
      - env:
        - name: DEIS_APP
          valueFrom:
            secretKeyRef:
              key: deis-app
              name: water-secret
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: log-level
              name: water-secret
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: water-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-url
              name: water-secret
        - name: WORKFLOW_RELEASE
          valueFrom:
            secretKeyRef:
              key: workflow-release
              name: water-secret
        - name: WORKFLOW_RELEASE_CREATED_AT
          valueFrom:
            secretKeyRef:
              key: workflow-release-created-at
              name: water-secret
        - name: WORKFLOW_RELEASE_SUMMARY
          valueFrom:
            secretKeyRef:
              key: workflow-release-summary
              name: water-secret
        image: ghcr.io/kingdonb/water-monitor/myapp:main-97a65e08-1733454308 # {"$imagepolicy": "cozy-fluxcd:dev-policy"}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: 4567
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 50
        name: water-cmd
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: water
  name: water
  namespace: water
spec:
  ports:
  - name: http
    port: 80
    targetPort: 4567
  selector:
    app: water
    type: cmd
