name: MiniTest (Ruby)

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  ruby-minitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Change directory to ruby
        run: cd ruby

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec ruby test_main.rb

