name: MiniTest (Ruby)

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  ruby-minitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@6825c765eb33355054208d865dd846da7da6584f # v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
          working-directory: ruby/

      - name: Run tests
        run: cd ruby && bundle exec ruby test_main.rb

